### ISSUE TITLE
Comments are completely hidden

### ISSUE THREAD

**Issue by rbozan** [JWW127/theink#1]
Hi, I'd like to use this colorscheme for my eink monitor, but the following line for comments make it really unusable:

https://github.com/JWW127/theink/blob/6ba739ecceeef4ee03a890b343fc7c3f558d8fa8/colors/theink.lua#L34

This totally fades in with the blue-ish background. Which I also suggest to adjust to something else, for example completely white:
https://github.com/JWW127/theink/blob/6ba739ecceeef4ee03a890b343fc7c3f558d8fa8/colors/theink.lua#L26

**Comment by JWW127** [comment]
@rbozan you are correct, I made changes to the points you highlighted. If you have any other issues feel free to open a pr. Or if you prefer forking the repo, send me a quick message and I will forward everyone to your updated version.

**Comment by rbozan** [comment]
@JWW127 I think someday I will make a fork as there are some other adjustments I'd like to make, but the theme you made is a good starting point so thanks for that!
